# FVG_DCA_Pro/languages.py

TRANSLATIONS = { 
    "zh-CN": {
        # --- 1. 通用 & 按钮 ---
        "title": "DCA Pro 量化系统",
        "loading": "加载中...",
        "connecting": "连接中...",
        "success": "成功",
        "error": "错误",
        "save": "保存配置",
        "cancel": "取消",
        "confirm": "确认",
        "running": "运行中",
        "stopped": "已停止",
        "back": "返回",
        "delete": "删除",
        "search": "搜索",
        "reset": "重置",
        "details": "详情",
        "actions": "操作",
        "refresh": "刷新",
        "close": "关闭",
        "create": "创建",
        "source": "来源",
        "enter_replay_mode": "进入重播模式",
        "exit_replay_mode": "退出重播 (返回实盘)",
        "replay_mode_active": "重播模式中",
        
        # --- 2. 身份认证 ---
        "login": "登录",
        "register": "注册",
        "logout": "退出登录",
        "back_to_login": "返回登录",
        "username": "用户名",
        "password": "密码",
        "Please_provide_complete_information": "请填写完整信息",
        "login_failed": "用户名或密码错误",
        "username_exists": "用户名已存在",
        "registration_success": "注册成功，请登录",
        
        # --- 3. 管理员/用户管理 ---
        "settings": "系统设置",
        "management": "管理",
        "together": "共",
        "people": "人",
        "role": "角色",
        "registration_time": "注册时间",
        "bot_count": "机器人数量",
        "total_profit_estimate": "总盈亏估算",
        "admin": "管理员",
        "user": "用户",
        "view_users": "查看用户",
        "no_users_found": "未找到匹配的用户",
        "admin_dashboard": "管理员后台",
        "need_admin": "需要管理员权限",

        # --- 4. 仪表盘 (Dashboard) ---
        "dashboard_title": "机器人实例管理",
        "floating_pnl": "浮动盈亏",
        "enter_details": "进入详情",
        "delete_confirm": "⚠️ 警告：确定删除该实例吗？此操作不可逆。",
        "no_bot_instances": "暂无机器人实例",
        "click_add_new_bot": "点击右上角“添加新机器人”开始交易",
        
        # --- 5. 创建/添加机器人 ---
        "add_bot": "添加新机器人",
        "bot_name": "机器人名称",
        "give_your_bot_a_name": "给你的机器人起个名字",
        "symbol": "交易对",
        "loading_symbol_list": "正在从币安获取列表...",
        "bot": "机器人类型",
        "capital": "初始投入",
        "fvg_martingale": "FVG DCA (马丁)",
        "auto_grid": "Auto Grid DCA (自动区间)",
        "coffin": "Coffin 战法 (箱体突破)",
        "Invalid_symbol_format": "交易对格式错误，请使用如 BTC/USDT 的格式",
        "Create_failed": "创建失败",
        "leverage_must_be_gte_1": "杠杆倍数必须大于等于 1",
        "search_symbol_placeholder": "搜索或输入 (如 BTC/USDT)",
        "symbol_not_supported": "该交易对未在币安合约列表中找到，请检查拼写。",

        # --- 6. 交易详情页 - 概览 ---
        "market_price": "当前市价 (USD)",
        "balance": "可用余额",
        "deposit_increase_capital": "充值/增加投入",
        "realized_pnl": "交易毛利",
        "start_bot": "🚀 启动机器人",
        "stop_bot": "🛑 停止运行",
        "upload_history_csv": "📂 上传历史数据 (.csv)",
        "run_backtest": "▶️ 开始回测",
        "bot_params": "机器人参数",
        "market_type": "市场类型",
        "future": "Futures (合约)", 
        "spot": "Spot (现货)",
        "leverage": "杠杆倍数",
        "long": "做多",
        "short": "做空",
        "both": "多空皆做",
        
        # --- 7. 交易详情页 - 操作与持仓 ---
        "manual_buy": "手动买入",
        "manual_close": "🚨 市价全平",
        "manual_close_confirm": "⚠️ 危险操作：确定要按市价全平吗？",
        "pos_avg": "持仓均价",
        "pos_amt": "持仓数量",
        "pos_cost": "持仓保证金",
        "pos_direction": "方向",
        "no_position": "无持仓",
        "manual_buy_amount": "加仓金额",
        "please_enter_valid_manual_buy_amount": "请输入有效的加仓金额",
        "placing_order": "下单中...",
        "current_position": "当前持有仓位",
        "manual_buy_success": "手动买入成功",
        "manual_close_success": "已市价平仓",
        
        # --- 8. 资金管理 & 弹窗 ---
        "deposit_amount": "增加授权资金 (USDT)",
        "deposit_security_title": "🛡️ 资金隔离保护模式",
        "deposit_security_hint": "此金额是该机器人的<b>最大授权动用额度</b>。<br>• 机器人<b>仅</b>被允许使用这笔资金进行交易。<br>• 即使交易所账户仍有余额，本金耗尽后机器人也会立即停止。<br>• <b>绝不挪用</b>您账户中的其余资金。<br>",
        "deposit_instructions": "* 这将增加余额和机器人总投入。<br>* 机器人会基于新的总资金重新计算下单量。",
        "deposit": "充值",
        "processing": "处理中",
        "deposit_success": "已充值",
        "deposit_success_msg": "充值成功！", 
        "deposit_failed": "充值失败",
        "amount_must_be_positive": "金额必须大于0",
        "balances": "余额",
        "total_investment": "总投入",

        # --- 9. 图表与状态 ---
        "kline_chart": "K线图",
        "tf_1m": "1分钟",
        "tf_3m": "3分钟",
        "tf_5m": "5分钟",
        "tf_15": "15分钟",
        "tf_1h": "1小时",
        "tf_4h": "4小时",
        "tf_1d": "1天",
        "tf_1w": "1周",
        "trail_status": "追踪止盈状态",
        "not_activated": "未激活",
        "activated": "已激活",
        "trail_high": "极值价格",
        "distance_avg_drawdown": "距离均价(回撤)",
        "current_state_machine": "当前状态机",
        
        # --- 10. 机器人特定参数 (Grid/DCA/Coffin) ---
        "ladder_preview": "补仓梯子预览",
        "grid_ladder": "网格挂单预览",
        "box_range_5m": "5m 箱体范围",
        "current_sl": "当前止损", 
        "retest_tolerance": "回踩容差",
        "retest_tolerance_desc": "离箱体多远算回踩成功",
        "box_height": "箱体高度",
        "box_height_desc": "箱体高度百分比 (如 5% 则输入 5)",
        "be_trigger": "保本触发",
        "be_trigger_desc": "盈利多少%后止损移至开仓价",
        "trailing_gap": "追踪回撤",
        "trailing_gap_desc": "从最高点回撤多少%止盈",
        "cooldown_seconds": "交易冷却 (秒)",
        "cooldown_seconds_desc": "<b>防止死循环磨损</b><br>平仓后多少秒内禁止再次开仓。<br>建议至少 60 秒，震荡行情建议调大。",
        "realized_profit": "交易毛利",
        "net_pnl": "净盈亏",
        "total_fees": "总手续费",
        "max_orders": "最大单数",
        "fvg_tfs": "FVG 监控时段 (逗号分隔)",
        "vol_scale": "投倍",
        "step_percent": "首单间距 %",
        "step_scale": "间距倍数",
        "tp_target": "止盈目标 %",
        "sl_percent": "止损 %",
        "trailing_dev": "回撤 %",
        "fee_rate": "手续费率",
        "fee_rate_desc": "<b>交易手续费率</b><br>币安合约 Taker 通常为 0.0005 (0.05%)。<br>设置过低会导致显示的净利润虚高。",
        "amount_precision": "下单精度",
        "amount_precision_desc": "<b>⚠️ 重要：数量精度 (Step Size)</b><br>决定下单数量的小数位数。<br>例如：<br>• BTC/ETH 填 0.001<br>• DOGE/XRP 填 1 (整数)<br>填错会导致 'Invalid Quantity' 报错。",
        "order_amount_single": "单次开仓金额 (USDT)",
        "order_amount_hint": "设置 0 则默认使用全部资金开仓",
        "all_in_placeholder": "0 = 梭哈 (使用全部资金)",
        "close_action": "手动平仓后行为",
        "cooldown_1h": "冷却 1小时",
        "continue_running": "继续运行",
        "trigger_price": "触发价",
        "current_order_usdt": "本单($)",
        "cumulative_usdt": "累计($)",
        "drawdown_percent": "跌幅%",
        "status": "状态",
        "range_top": "区间顶部",
        "range_bottom": "区间底部",
        "range_percent": "跌幅区间 %",
        "grid_count": "网格数量",
        "grid_distribution_type": "网格分布类型",
        "arithmetic": "Arithmetic (等差 - 相同价差)",
        "geometric": "Geometric (等比 - 相同利润)",
        "grid_distribution_type_desc": "* 等差：首单区间较窄；等比：所有区间百分比一致。",
        "current_effective_range": "当前生效区间",
        "current_grid_anchor": "当前网格锚点",
        "average_drawdown": "平均跌幅 %",
        "position_status": "持仓状态",
        "price": "价格",
        "fee": "手续费",
        "amount": "数量",
        "running_round": "进行中",
        "grid": "网格",
        "range_info": "区间",
        "sl_hit": "触发止损",
        "trailing_hit": "追踪触发",
        "periodic_investment": "定投策略",
        "periodic_interval_minute": "定投间隔 (分钟)",
        "periodic_interval_desc": "每隔多少分钟自动买入一次",
        "invest_amount": "定投金额 (USDT)",
        "price_limit_long": "价格上限 (高于此价不买)",
        "price_limit_short": "价格下限 (低于此价不卖)",
        "price_limit_desc": "0 表示不限制。做多时：价格太高不买；做空时：价格太低不空。",
        "leverage_max_3": "定投策略最大杠杆为 3倍",
        "next_invest_time": "下次定投时间",
        "waiting_interval": "等待定投时间",
        "price_too_high": "价格过高，暂停定投",
        "price_too_low": "价格过低，暂停定投",
        "periodic_buy": "定投买入",

        # --- 11. 日志与记录 (前端显示) ---
        "history_tab": "🧾 交易记录",
        "logs_tab": "📜 系统日志",
        "status_waiting": "等待",
        "status_monitoring": "监控中",
        "status_filled": "已成交",
        "no_data_or_no_market_data": "暂无数据或未获取行情",
        "no_data_or_waiting_for_range": "暂无数据或请等待区间生成",
        "no_trade_records": "暂无交易记录",

        # --- 12. 设置页 ---
        "settings_title": "⚙️ 系统设置",
        "language_select": "语言选择 (Language)",
        "save_settings": "保存设置",
        "config_saved": "配置已保存！",
        "save_failed": "保存失败",
        "api_data_source": "API 数据源",
        "api_source_desc": "选择行情数据来源。切换后，所有机器人将使用该交易所的数据（K线、市价等）运行。",
        "current": "当前",
        "api_config_title": "API 配置",
        "api_key_label": "API Key (公钥)",
        "api_secret_label": "API Secret (私钥)",
        "enter_api_key": "请输入 API Key",
        "enter_api_secret": "请输入 API Secret",
        "api_key_desc": "请输入您所选交易所的 API Key 和 Secret。系统将使用它们进行下单和账户验证。",
        "security_warning": "安全提示：您的 API Key 仅存储用于交易授权，请勿分享给他人。",

        # --- 13. 错误与系统消息 ---
        "Network_request_failed": "网络请求失败",
        "Delete_failed": "删除失败",
        "load_failed": "加载失败，请刷新重试",
        "delete_confirm_long": "⚠️ 警告：\n确定删除该实例吗？\n\n1. 交易历史将被清空\n2. 请确保已经在交易所平仓\n3. 删除后无法恢复",
        "unknown_error": "未知错误",
        "network_error_title": "⚠️ 网络连接失败 (Network Error)！",
        "network_error_hint": "无法获取 K 线或行情数据，请检查：\n1. VPN/代理 是否已开启全局模式？\n2. 服务器是否能访问 Binance API？\n3. 请尝试刷新页面。",
        "no_permission_to_access_this_bot": "无权访问此机器人",
        "instance_not_found": "实例不存在",
        "delete_rejected_due_to_open_position": "拒绝删除：当前仍有持仓",
        "please_close_position_first": "请先手动平仓",
        "delete_rejected_due_to_running_bot": "拒绝删除：机器人正在运行中",
        "please_stop_running_first": "请先停止运行",
        "dangerous_operation_intercepted": "危险操作被拦截！",
        "flash_unauthorized_action": "无权操作",
        "amount_format_error": "金额格式错误",
        "bot_not_found": "机器人未找到",
        "connection_failed": "连接失败",
        "user_not_found": "用户不存在",
        "invalid_language": "无效的语言选择",
        "err_price_fetch": "无法获取价格",
        "err_price_fetch_retry": "无法获取当前价格，请检查网络或稍后再试",
        "err_qty_too_small": "数量过小",
        "err_order_amount_too_small": "计算出的下单数量过小，无法执行",

        # === 14. 后端日志与状态机 ===
        "log_base_order": "首单",
        "log_buy": "买入",
        "log_sell": "卖出",
        "log_manual_buy": "手动买入",
        "log_manual_close": "手动平仓",
        "log_stop_loss": "止损平仓",
        "log_take_profit": "止盈平仓",
        "log_trailing_active": "激活追踪",
        "log_trailing_hit": "追踪止盈触发",
        "log_dca_buy": "补仓",
        "log_grid_buy": "网格买入",
        "log_deposit": "充值/入金",
        "status_running": "🟢 运行中",
        "status_order_pending": "⏳ 挂单",
        "status_starting": "🟡 启动中...",
        "status_stopped": "🛑 已停止",
        "status_cooldown": "🧊 冷却中",
        "status_waiting_range": "⏳ 等待区间生成",
        "status_insufficient_balance": "⚠️ 余额不足",
        "msg_manual_buy_success": "手动加仓成功",
        "msg_manual_close_success": "手动平仓完成",
        "base_order_market": "基础订单（市场）",
        "interval_reset": " (区间重置)",
        "tracking_profits": "追踪止盈",
        "just_traded_waiting_for_deviation": "⏳ 刚交易过，等待价格偏离...",
        "insufficient_balance_stop_replenishment": "⚠️ 余额耗尽，停止补单",
        "first_order_area": "(首单区域)",
        "state_fix_enter_pos": "状态修复: 进入持仓模式",
        "state_fix_reset_fake_pos": "状态修复: 重置虚拟持仓",
        "waiting_for_kline": "等待 K 线数据...",
        "auto_emergency_sl": "自动生成应急止损",
        "trigger_be": "触发保本止损",
        "trailing_sl_up": "追踪止损上移",
        "trailing_sl_down": "追踪止损下移",
        "extreme_value": "极值",
        "detected": "监测到",
        "breakout_waiting_retest": "突破! 等待回踩...",
        "scanning": "扫描中",
        "false_breakout_reset": "假突破，重置监测",
        "retest_entry": "回踩进场",
        "waiting_for_retest": "等待回踩... 距离",
        "trigger_take_profit_trailing": "触发止盈，追踪中...",
        "need": "需",
        "have": "有",
        "manual_warehousing": "手动加仓",
        "direction_change_forbidden": "禁止切换方向",
        "please_manual_close_first": "请先【手动全平】后再修改方向。",
        "direction_changed_bot_reset": "方向变更，机器人状态已重置。",
        "changed_bot_reset": "变更，区间已重置。",
        "range_changed_anchor_reset": "区间变更，锚点已重置。",
        "status_reset": "状态已重置", 

        # --- 15. 布局与文件夹 [补齐分类] ---
        "layout_bot": "机器人视图",
        "layout_custom": "自定义视图",
        "create_folder": "新建分类",
        "folder_name": "分类名称",
        "select_bots": "选择机器人 (仅显示未分类)",
        "uncategorized": "未分类 / 默认",
        "delete_folder": "删除分类",
        "delete_folder_confirm": "确定删除此分类吗？分类下的机器人将变为未分类。",
        "move_to": "移动到...",
        "all_bots_categorized": "所有机器人已分类！",
        "folder_created": "分类创建成功",
        "folder_deleted": "分类已删除",
        "bot_moved": "机器人已移动",

        # [新增] RSI 过滤器相关
        'first_order_settings': '📉 开单信号设置',
        'first_order_conditions': '首单开仓条件 (仅限首单)',
        'rsi_conditions_title': 'RSI 开单条件',
        'timeframe': '周期',
        'operator': '比较符',
        'threshold': 'RSI 数值',
        'active': '启用',
        'add_condition': '+ 添加条件',
        'delete': '删除',
        'op_lt': '小于 (<)',
        'op_gt': '大于 (>)',
        'rsi_help': '只有当所有启用的条件都满足时，机器人才会开首单。不影响补仓。',
        "hard_filters_title": "🛑 硬性指标过滤 (Hard Filters)",
        "enable_stoch_filter": "启用 StochRSI (15m K<20/K>80)",
        "enable_bb_filter": "启用布林带 (15m 突破上/下轨)",
        "enable_adx_filter": "启用 ADX (4h ADX < 25 避开单边)",
        "enable_vol_filter": "启用成交量爆发 (15m Vol > 1.5倍均量)", 
        "filter_wait_vol": "⏳ 过滤: 成交量不足 (Vol={v:.0f} < Target={t:.0f})",
        
        "filter_wait_stoch": "⏳ 过滤: StochRSI 不满足 (K={k:.1f})",
        "filter_wait_bb": "⏳ 过滤: 价格未突破布林带 (Price={p:.2f}, Band={b:.2f})",
        "filter_wait_adx": "⏳ 过滤: 4H 趋势过强 (ADX={adx:.1f} > 25)",
        "filter_wait_msg": "⏳ 等待指标共振: {details}",

        'ma_trend_filter': '📈 MA 趋势过滤',
        'ma_long': '做多 MA',
        'ma_short': '做空 MA',
        'ma_period': '均线周期',
        'ma_type': '类型',
        'ma_help': '做多时价格需高于 MA，做空时价格需低于 MA。',
        'filter_wait_ma': '⏳ 过滤: 价格不满足 MA 趋势 (Price={p:.2f}, MA={m:.2f})',
        'ma_period_hint': '中间的数字代表计算过去多少根 K 线 (如 50/100/200)。',
        'ma_type_hint': 'EMA (指数) 权重更偏向近期价格，更灵敏；SMA (简单) 为普通平均值。',

        # 数据下载相关
        "download_history_data": "下载历史数据",
        "download_modal_title": "📥 从交易所下载历史数据",
        "start_date": "开始日期",
        "end_date": "结束日期",
        "download_tip": "ℹ️ 下载速度取决于网络。建议下载范围不要超过 3-6 个月。",
        "coffin_warning": "⚠️ 注意：Coffin 机器人回测仅支持 5m 周期！",
        "search_symbol_placeholder": "输入或选择交易对 (如 BTC/USDT)",
        "start_download_btn": "开始下载 (.csv)",
        "downloading_wait": "⏳ 下载中... 请勿关闭窗口",
        "download_success_alert": "下载成功！现在你可以去重播模式上传这个 CSV 了。",
        "date_required": "请选择开始日期",
        "download_error": "下载失败",
        "start_date_end_date_required": "开始日期和结束日期不能为空",
        "end_date_must_be_later": "结束日期必须晚于开始日期",
        "date_format_error": "日期格式错误",
        "missing_bot_id_or_file": "缺少 bot_id 或文件",
        "backtest_completed": "回测完成",
        "backtest_failed": "回测失败",
        "please_upload_csv": "请先上传 CSV 文件！",
        "running_dots": "运行中...",
        "network_error_simple": "网络错误",
        "no_data_fetched": "未获取到数据",
        "backtest_success_msg": "回测完成！",

        'organizing_data': '数据整理中...',
        'loading_layout': '正在渲染界面...'
    },
    
    "zh-TW": {
        # --- 1. 通用 & 按鈕 ---
        "title": "DCA Pro 量化系統",
        "loading": "載入中...",
        "connecting": "連線中...",
        "success": "成功",
        "error": "錯誤",
        "save": "儲存設定",
        "cancel": "取消",
        "confirm": "確認",
        "running": "運行中",
        "stopped": "已停止",
        "back": "返回",
        "delete": "刪除",
        "search": "搜尋",
        "reset": "重置",
        "details": "詳情",
        "actions": "操作",
        "refresh": "重新整理",
        "close": "關閉",
        "create": "創建",
        "source": "來源",
        "enter_replay_mode": "進入重播模式",
        "exit_replay_mode": "退出重播 (返回實盤)",
        "replay_mode_active": "重播模式中",

        # --- 2. 身份認證 ---
        "login": "登入",
        "register": "註冊",
        "logout": "登出",
        "back_to_login": "返回登入",
        "username": "使用者名稱",
        "password": "密碼",
        "Please_provide_complete_information": "請填寫完整資訊",
        "login_failed": "使用者名稱或密碼錯誤",
        "username_exists": "使用者名稱已存在",
        "registration_success": "註冊成功，請登入",

        # --- 3. 管理員/用戶管理 ---
        "settings": "系統設定",
        "management": "管理",
        "together": "共",
        "people": "人",
        "role": "角色", 
        "registration_time": "註冊時間",
        "bot_count": "機器人數量",
        "total_profit_estimate": "總盈虧估算",
        "admin": "管理員",
        "user": "用戶",
        "view_users": "查看用戶",
        "no_users_found": "未找到匹配的用戶",
        "admin_dashboard": "管理員後臺",
        "need_admin": "需要管理員權限",

        # --- 4. 儀表盤 (Dashboard) ---
        "dashboard_title": "機器人實例管理",
        "floating_pnl": "浮動盈虧",
        "enter_details": "進入詳情",
        "delete_confirm": "⚠️ 警告：確定刪除該實例嗎？此操作不可逆。",
        "no_bot_instances": "暫無機器人實例",
        "click_add_new_bot": "點擊右上角“添加新機器人”開始交易",

        # --- 5. 創建/添加機器人 ---
        "add_bot": "添加新機器人",
        "bot_name": "機器人名稱",
        "give_your_bot_a_name": "給你的機器人起個名字",
        "symbol": "交易對",
        "loading_symbol_list": "正在從幣安獲取列表...",
        "bot": "機器人類型",
        "capital": "初始投入 (USDT)",
        "fvg_martingale": "FVG DCA (FVG 馬丁)",
        "auto_grid": "Auto Grid DCA (自動區間)",
        "coffin": "Coffin 戰法 (箱體突破)",
        "Invalid_symbol_format": "交易對格式錯誤，請使用如 BTC/USDT 的格式",
        "Create_failed": "創建失敗",
        "leverage_must_be_gte_1": "槓桿倍數必須大於等於 1",
        "search_symbol_placeholder": "搜尋或輸入 (如 BTC/USDT)",
        "symbol_not_supported": "該交易對未在幣安合約列表中找到，請檢查拼寫。",
        
        # --- 6. 交易詳情頁 - 概覽 ---
        "market_price": "當前市價 (USD)",
        "balance": "可用餘額",
        "deposit_increase_capital": "儲值/增加投入",
        "realized_pnl": "交易毛利",
        "start_bot": "🚀 啟動機器人",
        "stop_bot": "🛑 停止運行",
        "upload_history_csv": "📂 上傳歷史數據 (.csv)",
        "run_backtest": "▶️ 開始回測",
        "bot_params": "機器人參數",
        "market_type": "市場類型",
        "future": "Futures (合約)", 
        "spot": "Spot (現貨)",
        "leverage": "槓桿倍數",
        "long": "做多",
        "short": "做空",
        "both": "多空雙開",

        # --- 7. 交易詳情頁 - 操作與持倉 ---
        "manual_buy": "手動買入",
        "manual_close": "🚨 市價全平",
        "manual_close_confirm": "⚠️ 危險操作：確定要按市價全平嗎？",
        "pos_avg": "持倉均價",
        "pos_amt": "持倉數量",
        "pos_cost": "持倉保證金",
        "pos_direction": "方向",
        "no_position": "無持倉",
        "manual_buy_amount": "加倉金額",
        "please_enter_valid_manual_buy_amount": "請輸入有效的加倉金額",
        "placing_order": "下單中...",
        "current_position": "當前持有倉位",
        "manual_buy_success": "手動買入成功",
        "manual_close_success": "已市價平倉",

        # --- 8. 資金管理 & 彈窗 ---
        "deposit_amount": "增加授權資金 (USDT)",
        "deposit_security_title": "🛡️ 資金隔離保護模式",
        "deposit_security_hint": "此金額是該機器人的<b>最大授權動用額度</b>。<br>• 機器人<b>僅</b>被允許使用這筆資金進行交易。<br>• 即使交易所賬戶仍有餘額，本金耗盡後機器人也會立即停止。<br>• <b>絕不挪用</b>您賬戶中的其餘資金。<br>",
        "deposit_instructions": "* 這將增加餘額和機器人總投入。<br>* 機器人會基於新的總資金重新計算下單量。",
        "deposit": "儲值",
        "processing": "處理中",
        "deposit_success": "已儲值",
        "deposit_success_msg": "儲值成功！", 
        "deposit_failed": "儲值失敗",
        "amount_must_be_positive": "金額必須大於0",
        "balances": "餘額",
        "total_investment": "總投入",

        # --- 9. 圖表與狀態 ---
        "kline_chart": "K線圖",
        "tf_1m": "1分鐘",
        "tf_3m": "3分鐘",
        "tf_5m": "5分鐘",
        "tf_15": "15分鐘",
        "tf_1h": "1小時",
        "tf_4h": "4小時",
        "tf_1d": "1天",
        "tf_1w": "1週",
        "trail_status": "追蹤止盈狀態",
        "not_activated": "未激活",
        "activated": "已激活",
        "trail_high": "極值價格",
        "distance_avg_drawdown": "距離均價(回撤)",
        "current_state_machine": "當前狀態機",

        # --- 10. 机器人特定參數 (Grid/DCA/Coffin) ---
        "ladder_preview": "補倉梯子預覽",
        "grid_ladder": "網格掛單預覽",
        "box_range_5m": "5m 箱體範圍",
        "current_sl": "當前止損", 
        "retest_tolerance": "回踩容差",
        "retest_tolerance_desc": "離箱體多遠算回踩成功",
        "box_height": "箱體高度",
        "box_height_desc": "箱體高度百分比 (如 5% 則輸入 5)",
        "be_trigger": "保本觸發",
        "be_trigger_desc": "盈利多少%後止損移至開倉價",
        "trailing_gap": "追蹤回撤",
        "trailing_gap_desc": "從最高點回撤多少%止盈",
        "cooldown_seconds": "交易冷卻 (秒)",
        "cooldown_seconds_desc": "<b>防止死循環磨損</b><br>平倉後多少秒內<b>自動</b>開首單。<br>手動開倉不受限制。<br>建議至少 60 秒，震盪行情建議調大。",
        "realized_profit": "交易毛利",
        "net_pnl": "淨盈虧",
        "total_fees": "總手續費",
        "max_orders": "最大單數",
        "fvg_tfs": "FVG 監控時段 (逗號分隔)",
        "vol_scale": "投倍",
        "step_percent": "首單間距 %",
        "step_scale": "間距倍數",
        "tp_target": "止盈目標 %",
        "sl_percent": "止損 %",
        "trailing_dev": "回撤 %",
        "fee_rate": "手續費率",
        "fee_rate_desc": "<b>交易手續費率</b><br>幣安合約 Taker 通常為 0.0005 (0.05%)。<br>設置過低會導致顯示的淨利潤虛高。",
        "amount_precision": "下單精度",
        "amount_precision_desc": "<b>⚠️ 重要：數量精度 (Step Size)</b><br>決定下單數量的小數部分位數。<br>例如：<br>• BTC/ETH 填 0.001<br>• DOGE/XRP 填 1 (整數)<br>填錯會導致 'Invalid Quantity' 報錯。",
        "order_amount_single": "單次開倉金額 (USDT)",
        "order_amount_hint": "設置 0 則預設使用全部資金開倉",
        "all_in_placeholder": "0 = 梭哈 (使用全部資金)",
        "close_action": "手動平倉後行為",
        "cooldown_1h": "冷卻 1小時",
        "continue_running": "繼續運行",
        "trigger_price": "觸發價",
        "current_order_usdt": "本單(U)",
        "cumulative_usdt": "累計(U)",
        "drawdown_percent": "跌幅%",
        "status": "狀態",
        "range_top": "區間頂部",
        "range_bottom": "區間底部",
        "range_percent": "跌幅區間 %",
        "grid_count": "網格數量",
        "grid_distribution_type": "網格分佈類型",
        "arithmetic": "Arithmetic (等差 - 相同價差)",
        "geometric": "Geometric (等比 - 相同利潤)",
        "grid_distribution_type_desc": "* 等差：首單區間較窄；等比：所有區間百分比一致。",
        "current_effective_range": "當前生效區間",
        "current_grid_anchor": "當前網格錨點",
        "average_drawdown": "平均跌幅 %",
        "position_status": "持倉狀態",
        "price": "價格",
        "fee": "手續費",
        "amount": "數量",
        "running_round": "進行中",
        "grid": "網格",
        "range_info": "區間",
        "sl_hit": "觸發止損",
        "trailing_hit": "追蹤觸發",
        "periodic_investment": "定投策略 (Periodic)",
        "periodic_interval_minute": "定投間隔 (分鐘)",
        "periodic_interval_desc": "每隔多少分鐘自動買入一次",
        "invest_amount": "定投金額 (USDT)",
        "price_limit_long": "價格上限 (高於此價不買)",
        "price_limit_short": "價格下限 (低於此價不賣)",
        "price_limit_desc": "0 表示不限制。做多時：價格太高不買；做空時：價格太低不空。",
        "leverage_max_3": "定投策略最大槓桿為 3倍",
        "next_invest_time": "下次定投時間",
        "waiting_interval": "等待定投時間",
        "price_too_high": "價格過高，暫停定投",
        "price_too_low": "價格過低，暫停定投",
        "periodic_buy": "定投買入",

        # --- 11. 日誌與記錄 ---
        "history_tab": "🧾 交易記錄",
        "logs_tab": "📜 系統日誌",
        "status_waiting": "等待",
        "status_monitoring": "監控中",
        "status_filled": "已成交",
        "no_data_or_no_market_data": "暫無數據或未獲取行情",
        "no_data_or_waiting_for_range": "暫無數據或請等待區間生成",
        "no_trade_records": "暫無交易記錄",

        # --- 12. 設定頁 ---
        "settings_title": "⚙️ 系統設定",
        "language_select": "語言選擇 (Language)",
        "save_settings": "儲存設定",
        "config_saved": "配置已儲存！",
        "save_failed": "儲存失敗",
        "api_data_source": "API 數據源",
        "api_source_desc": "選擇行情數據來源。切換後，所有機器人將使用該交易所的數據（K線、市價等）運行。",
        "current": "當前",
        "api_config_title": "API 設定 (API Configuration)",
        "api_key_label": "API Key (公鑰)",
        "api_secret_label": "API Secret (私鑰)",
        "enter_api_key": "請輸入 API Key",
        "enter_api_secret": "請輸入 API Secret",
        "api_key_desc": "請輸入您所選交易所的 API Key 和 Secret。系統將使用它們進行下單和賬戶驗證。",
        "security_warning": "安全提示：您的 API Key 僅存儲用於交易授權，請勿分享給他人。",

        # --- 13. 錯誤與系統消息 ---
        "Network_request_failed": "網絡請求失敗",
        "Delete_failed": "刪除失敗",
        "load_failed": "加載失敗，請刷新重試",
        "delete_confirm_long": "⚠️ 警告：\n確定刪除該實例嗎？\n\n1. 交易記錄將被清空\n2. 請確保已經在交易所平倉\n3. 刪除後無法恢復",
        "unknown_error": "未知錯誤",
        "network_error_title": "⚠️ 網絡連接失敗 (Network Error)！",
        "network_error_hint": "無法獲取 K 線或行情數據，請檢查：\n1. VPN/代理 是否已開啓全局模式？\n2. 服務器是否能訪問 Binance API？\n3. 請嘗試刷新頁面。",
        "no_permission_to_access_this_bot": "無權訪問此機器人",
        "instance_not_found": "實例不存在",
        "delete_rejected_due_to_open_position": "拒絕刪除：當前仍有持倉",
        "please_close_position_first": "請先手動平倉",
        "delete_rejected_due_to_running_bot": "拒絕刪除：機器人正在運行中",
        "please_stop_running_first": "請先停止運行",
        "dangerous_operation_intercepted": "危險操作被攔截！",
        "flash_unauthorized_action": "無權操作",
        "amount_format_error": "金額格式錯誤",
        "bot_not_found": "機器人未找到",
        "connection_failed": "連接失敗",
        "user_not_found": "用戶不存在",
        "invalid_language": "無效的語言選擇",
        "err_price_fetch": "無法獲取價格",
        "err_price_fetch_retry": "無法獲取當前價格，請檢查網絡或稍後再試",
        "err_qty_too_small": "數量過小",
        "err_order_amount_too_small": "計算出的下單數量過小，無法執行",
    
        # === 14. 後端日誌與狀態機 ===
        "log_base_order": "首單",
        "log_buy": "買入",
        "log_sell": "賣出",
        "log_manual_buy": "手動買入",
        "log_manual_close": "手動平倉",
        "log_stop_loss": "止損平倉",
        "log_take_profit": "止盈平倉",
        "log_trailing_active": "激活追蹤",
        "log_trailing_hit": "追蹤止盈觸發",
        "log_dca_buy": "補倉",
        "log_grid_buy": "網格買入",
        "log_deposit": "儲值/入金",
        "status_running": "🟢 運行中",
        "status_order_pending": "⏳ 掛單",
        "status_starting": "🟡 啟動中...",
        "status_stopped": "🛑 已停止",
        "status_cooldown": "🧊 冷卻中",
        "status_waiting_range": "⏳ 等待區間生成",
        "status_insufficient_balance": "⚠️ 餘額不足",
        "msg_manual_buy_success": "手動加倉成功",
        "msg_manual_close_success": "手動平倉完成",
        "base_order_market": "基礎訂單（市價）",
        "interval_reset": " (區間重置)",
        "tracking_profits": "追蹤止盈",
        "just_traded_waiting_for_deviation": "⏳ 剛交易過，等待價格偏離...",
        "insufficient_balance_stop_replenishment": "⚠️ 餘額耗盡，停止補單",
        "first_order_area": "(首單區域)",
        "state_fix_enter_pos": "狀態修復: 進入持倉模式",
        "state_fix_reset_fake_pos": "狀態修復: 重置虛擬持仓",
        "waiting_for_kline": "等待 K 線數據...",
        "auto_emergency_sl": "自動生成應急止損",
        "trigger_be": "觸發保本止損",
        "trailing_sl_up": "追蹤止損上移",
        "trailing_sl_down": "追蹤止損下移",
        "extreme_value": "極值",
        "detected": "監測到",
        "breakout_waiting_retest": "突破! 等待回踩...",
        "scanning": "掃描中",
        "false_breakout_reset": "假突破，重置監測",
        "retest_entry": "回踩進場",
        "waiting_for_retest": "等待回踩... 距離",
        "trigger_take_profit_trailing": "觸發止盈，追蹤中...",
        "need": "需",
        "have": "有",
        "manual_warehousing": "手動加倉",
        "direction_change_forbidden": "禁止切換方向",
        "please_manual_close_first": "請先【手動全平】後再修改方向。",
        "direction_changed_bot_reset": "方向變更，機器人狀態已重置。",
        "changed_bot_reset": "變更，區間已重置。",
        "range_changed_anchor_reset": "區間變更，錨點已重置。",
        "status_reset": "狀態已重置", 

        # --- 15. 佈局與文件夾 [補齊] ---
        "layout_bot": "機器人視圖",
        "layout_custom": "自定義視圖",
        "create_folder": "新建分類",
        "folder_name": "分類名稱",
        "select_bots": "選擇機器人 (僅顯示未分類)",
        "uncategorized": "未分類 / 默認",
        "delete_folder": "刪除分類",
        "delete_folder_confirm": "確定刪除此分類嗎？分類下的機器人將變為未分類。",
        "move_to": "移動到...",
        "all_bots_categorized": "所有機器人已分類！",
        "folder_created": "分類創建成功",
        "folder_deleted": "分類已刪除",
        "bot_moved": "機器人已移動",

        # [新增] RSI 过滤器相关
        'first_order_settings': '📉 開單訊號設定',
        'first_order_conditions': '首單開倉條件 (僅限首單)',
        'rsi_conditions_title': 'RSI 開單條件 (僅限首單)',
        'timeframe': '週期',
        'operator': '比較符',
        'threshold': 'RSI 數值',
        'active': '啓用',
        'add_condition': '+ 添加條件',
        'op_lt': '小於 (<)',
        'op_gt': '大於 (>)',
        'rsi_help': '只有當所有啓用的條件都滿足時，機器人才會開首單。不影響補倉。',
        "hard_filters_title": "🛑 硬性指標過濾 (Hard Filters)",
        "enable_stoch_filter": "啟用 StochRSI (15m K<20/K>80)",
        "enable_bb_filter": "啟用布林帶 (15m 突破上/下軌)",
        "enable_adx_filter": "啟用 ADX (4h ADX < 25 避開單邊)",
        "enable_vol_filter": "啟用成交量爆發 (15m Vol > 1.5倍均量)",
        "filter_wait_vol": "⏳ 過濾: 成交量不足 (Vol={v:.0f} < Target={t:.0f})",

        "filter_wait_stoch": "⏳ 過濾: StochRSI 不滿足 (K={k:.1f})",
        "filter_wait_bb": "⏳ 過濾: 價格未突破布林帶 (Price={p:.2f}, Band={b:.2f})",
        "filter_wait_adx": "⏳ 過濾: 4H 趨勢過強 (ADX={adx:.1f} > 25)",
        "filter_wait_msg": "⏳ 等待指標共振: {details}",

        'ma_trend_filter': '📈 MA 趨勢過濾',
        'ma_long': '做多 MA',
        'ma_short': '做空 MA',
        'ma_period': '均線週期',
        'ma_type': '類型',
        'ma_help': '做多時價格需高於 MA，做空時價格需低於 MA。',
        'filter_wait_ma': '⏳ 過濾: 價格不滿足 MA 趨勢 (Price={p:.2f}, MA={m:.2f})',
        'ma_period_hint': '中間的數字代表計算過去多少根 K 線 (如 50/100/200)。',
        'ma_type_hint': 'EMA (指數) 權重更偏向近期價格，更靈敏；SMA (簡單) 為普通平均值。',

        # 数据下载相关
        "download_history_data": "下載歷史數據",
        "download_modal_title": "📥 從交易所下載歷史數據",
        "start_date": "開始日期",
        "end_date": "結束日期",
        "download_tip": "ℹ️ 下載速度取決於網絡。建議下載範圍不要超過 3-6 個月。",
        "coffin_warning": "⚠️ 注意：Coffin (戰法) 機器人回測僅支持 5m 週期！",
        "search_symbol_placeholder": "輸入或選擇交易對 (如 BTC/USDT)",
        "start_download_btn": "開始下載 (.csv)",
        "downloading_wait": "⏳ 下載中... 請勿關閉視窗",
        "download_success_alert": "下載成功！現在你可以去重播模式上傳這個 CSV 了。",
        "date_required": "請選擇開始日期",
        "download_error": "下載失敗",
        "start_date_end_date_required": "開始日期和結束日期不能為空",
        "end_date_must_be_later": "結束日期必須晚於開始日期",
        "date_format_error": "日期格式錯誤",
        "missing_bot_id_or_file": "缺少 bot_id 或文件",
        "backtest_completed": "回測完成",
        "backtest_failed": "回測失敗",
        "please_upload_csv": "請先上傳 CSV 文件！",
        "running_dots": "運行中...",
        "network_error_simple": "網絡錯誤",
        "no_data_fetched": "未獲取到數據",
        "backtest_success_msg": "回測完成！",

        'organizing_data': '數據整理中...',
        'loading_layout': '正在渲染介面...'
    },
    
    "en": {
        # --- 1. General & Buttons ---
        "title": "DCA Pro System",
        "loading": "Loading...",
        "connecting": "Connecting...",
        "success": "Success",
        "error": "Error",
        "save": "Save Config",
        "cancel": "Cancel",
        "confirm": "Confirm",
        "running": "Running",
        "stopped": "Stopped",
        "back": "Back",
        "delete": "Delete",
        "search": "Search",
        "reset": "Reset",
        "details": "Details",
        "actions": "Actions",
        "refresh": "Refresh",
        "close": "Close",
        "create": "Create",
        "source": "Source",
        "enter_replay_mode": "Enter Replay Mode",
        "exit_replay_mode": "Exit Replay (Live)",
        "replay_mode_active": "Replay Mode Active",
        
        # --- 2. Auth ---
        "login": "Login",
        "register": "Register",
        "logout": "Logout",
        "back_to_login": "Back to Login",
        "username": "Username",
        "password": "Password",
        "Please_provide_complete_information": "Please provide complete information",
        "login_failed": "Invalid username or password",
        "username_exists": "Username already exists",
        "registration_success": "Registration successful, please login",
        
        # --- 3. Admin/User Management ---
        "settings": "Settings",
        "management": "Management",
        "together": "Total",
        "people": "Users",
        "role": "Role", 
        "registration_time": "Registration Time",
        "bot_count": "Bot Count",
        "total_profit_estimate": "Est. Total Profit",
        "admin": "Admin",
        "user": "User",
        "view_users": "View Users",
        "no_users_found": "No users found",
        "admin_dashboard": "Admin Dashboard",
        "need_admin": "Administrator permission required",

        # --- 4. Dashboard ---
        "dashboard_title": "Bot Management",
        "floating_pnl": "Floating PnL",
        "enter_details": "Details",
        "delete_confirm": "⚠️ Warning: Are you sure you want to delete this instance? This action cannot be undone.",
        "no_bot_instances": "No bot instances",
        "click_add_new_bot": "Click 'Add New Bot' at top right to start",

        # --- 5. Add Bot ---
        "add_bot": "Add New Bot",
        "bot_name": "Bot Name",
        "give_your_bot_a_name": "Name your Bot",
        "symbol": "Symbol",
        "loading_symbol_list": "Loading list from Binance...",
        "bot": "bot Type",
        "capital": "Initial Capital (USDT)",
        "fvg_martingale": "FVG DCA (FVG Martingale)",
        "auto_grid": "Auto Grid DCA",
        "coffin": "Coffin Bot (Box Breakout)",
        "Invalid_symbol_format": "Invalid symbol format, use e.g. BTC/USDT",
        "Create_failed": "Creation Failed",
        "leverage_must_be_gte_1": "Leverage must be >= 1",
        "search_symbol_placeholder": "Search or type (e.g. BTC/USDT)",
        "symbol_not_supported": "Symbol not found in Binance list, please check.",
        
        # --- 6. Bot Details - Overview ---
        "market_price": "Market Price (USD)",
        "balance": "Avail. Balance",
        "deposit_increase_capital": "Deposit/Add Capital",
        "realized_pnl": "Trading PnL",
        "start_bot": "🚀 Start Bot",
        "stop_bot": "🛑 Stop Bot",
        "upload_history_csv": "📂 Upload History (.csv)",
        "run_backtest": "▶️ Run Backtest",
        "bot_params": "Bot Params",
        "market_type": "Market Type",
        "future": "Futures", 
        "spot": "Spot",
        "leverage": "Leverage",
        "long": "Long",
        "short": "Short",
        "both": "Both Sides",

        # --- 7. Bot Details - Positions ---
        "manual_buy": "Manual Buy",
        "manual_close": "🚨 Market Close All",
        "manual_close_confirm": "⚠️ Danger: Are you sure you want to close all positions at market price?",
        "pos_avg": "Entry Price",
        "pos_amt": "Size (Amt)",
        "pos_cost": "Margin (Cost)",
        "pos_direction": "Direction",
        "no_position": "No Position",
        "manual_buy_amount": "Buy Amount (USDT)",
        "please_enter_valid_manual_buy_amount": "Please enter a valid amount",
        "placing_order": "Placing order...",
        "current_position": "Current Position",
        "manual_buy_success": "Manual Buy Success",
        "manual_close_success": "All positions closed at market",

        # --- 8. Funds & Modals ---
        "deposit_amount": "Increase Authorized Capital (USDT)",
        "deposit_security_title": "🛡️ Capital Isolation Mode",
        "deposit_security_hint": "This amount is the <b>Maximum Authorized Limit</b> for this bot.<br>• The bot is <b>ONLY</b> allowed to use this amount.<br>• Even if your exchange account has more funds, the bot stops when this capital is exhausted.<br>• It will <b>NEVER</b> touch other funds in your account.<br>",
        "deposit_instructions": "* This increases balance and total Bot capital.<br>* Order sizes will be recalculated based on new total capital.",
        "deposit": "Deposit",
        "processing": "Processing...",
        "deposit_success": "Deposited",
        "deposit_success_msg": "Deposit Successful!", 
        "deposit_failed": "Deposit Failed",
        "amount_must_be_positive": "Amount must be positive",
        "balances": "Balances",
        "total_investment": "Total Invested",

        # --- 9. Charts & Status ---
        "kline_chart": "Chart",
        "tf_1m": "1m",
        "tf_3m": "3m",
        "tf_5m": "5m",
        "tf_15": "15m",
        "tf_1h": "1h",
        "tf_4h": "4h",
        "tf_1d": "1d",
        "tf_1w": "1w",
        "trail_status": "Trailing Status",
        "not_activated": "Inactive",
        "activated": "Active",
        "trail_high": "High Watermark",
        "distance_avg_drawdown": "Dist. from Avg (Drawdown)",
        "current_state_machine": "Current State",

        # --- 10. bot Specifics ---
        "ladder_preview": "DCA Ladder Preview",
        "grid_ladder": "Grid Orders Preview",
        "box_range_5m": "5m Box Range",
        "current_sl": "Current SL", 
        "retest_tolerance": "Retest Tolerance",
        "retest_tolerance_desc": "Distance to box for valid retest",
        "box_height": "Box Height",
        "box_height_desc": "Box height percentage (e.g., enter 5 for 5%)",
        "be_trigger": "Break-even Trigger",
        "be_trigger_desc": "Profit % to move SL to entry price",
        "trailing_gap": "Trailing Gap",
        "trailing_gap_desc": "Retracement % from peak to take profit",
        "cooldown_seconds": "Cooldown (Sec)",
        "cooldown_seconds_desc": "<b>Prevent Loop Churning</b><br>Seconds to wait after closing before re-opening.<br>Recommended: at least 60s; increase for volatile markets.",
        "realized_profit": "Trading PnL",
        "net_pnl": "Net PnL",
        "total_fees": "Total Fees",
        "max_orders": "Max Orders",
        "fvg_tfs": "FVG Timeframes (comma-separated)",
        "vol_scale": "Vol Scale (Multiplier)",
        "step_percent": "First Step %",
        "step_scale": "Step Scale",
        "tp_target": "TP Target %",
        "sl_percent": "Stop Loss %",
        "trailing_dev": "Trailing Deviation %",
        "fee_rate": "Fee Rate",
        "fee_rate_desc": "<b>Trading Fee Rate</b><br>Binance Futures Taker is usually 0.0005 (0.05%).<br>Setting this too low will show inflated net profits.",
        "amount_precision": "Order Precision",
        "amount_precision_desc": "<b>⚠️ Important: Quantity Step Size</b><br>Decimals allowed for order quantity.<br>E.g.:<br>• BTC/ETH: 0.001<br>• DOGE/XRP: 1 (Integer)<br>Wrong values cause 'Invalid Quantity' errors.",
        "order_amount_single": "Single Order Amount (USDT)",
        "order_amount_hint": "Set 0 to use full capital (All In)",
        "all_in_placeholder": "0 = All In (Full Capital)",
        "close_action": "Action After Manual Close",
        "cooldown_1h": "Cooldown 1h",
        "continue_running": "Continue Running",
        "trigger_price": "Trigger Price",
        "current_order_usdt": "Order (USDT)",
        "cumulative_usdt": "Total (USDT)",
        "drawdown_percent": "Drop %",
        "status": "Status",
        "range_top": "Range Top",
        "range_bottom": "Range Bottom",
        "range_percent": "Range Size %",
        "grid_count": "Grid Count",
        "grid_distribution_type": "Grid Type",
        "arithmetic": "Arithmetic (Equal Price Diff)",
        "geometric": "Geometric (Equal Ratio)",
        "grid_distribution_type_desc": "* Arithmetic: Tighter initial grids; Geometric: Equal percentage per grid.",
        "current_effective_range": "Effective Range (Read-only)",
        "current_grid_anchor": "Grid Anchor",
        "average_drawdown": "Avg Drawdown %",
        "position_status": "Pos Status",
        "price": "Price",
        "fee": "Fee",
        "amount": "Amount",
        "running_round": "Round Active",
        "grid": "Grid",
        "range_info": "Range",
        "sl_hit": "SL Hit",
        "trailing_hit": "Trailing Hit",
        "periodic_investment": "Periodic Inv. (DCA)",
        "periodic_interval_minute": "Interval (minute)",
        "periodic_interval_desc": "Buy every X minute",
        "invest_amount": "Invest Amount (USDT)",
        "price_limit_long": "Max Price Cap (Don't Buy Above)",
        "price_limit_short": "Min Price Floor (Don't Short Below)",
        "price_limit_desc": "0 = No limit. Long: skip if expensive; Short: skip if cheap.",
        "leverage_max_3": "Max leverage for Periodic is 3x",
        "next_invest_time": "Next Invest Time",
        "waiting_interval": "Waiting Interval",
        "price_too_high": "Price too high, skipping",
        "price_too_low": "Price too low, skipping",
        "periodic_buy": "Periodic Buy",

        # --- 11. Logs & History ---
        "history_tab": "🧾 Trade History",
        "logs_tab": "📜 System Logs",
        "status_waiting": "Waiting",
        "status_monitoring": "Monitoring",
        "status_filled": "Filled",
        "no_data_or_no_market_data": "No data or market data unavailable",
        "no_data_or_waiting_for_range": "No data or waiting for range generation",
        "no_trade_records": "No trade records found",

        # --- 12. Settings ---
        "settings_title": "⚙️ System Settings",
        "language_select": "Language",
        "save_settings": "Save Settings",
        "config_saved": "Configuration Saved!",
        "save_failed": "Save Failed",
        "api_data_source": "API Data Source",
        "api_source_desc": "Select market data source. All bots will use data (Kline, Price) from this exchange.",
        "current": "Current",
        "api_config_title": "API Configuration",
        "api_key_label": "API Key",
        "api_secret_label": "API Secret",
        "enter_api_key": "Enter API Key",
        "enter_api_secret": "Enter API Secret",
        "api_key_desc": "Please enter the API Key and Secret for your selected exchange.",
        "security_warning": "Security Warning: Keys are stored for trading authentication only. Do not share them.",

        # --- 13. Errors & Messages ---
        "Network_request_failed": "Network Request Failed",
        "Delete_failed": "Delete Failed",
        "load_failed": "Load failed, please refresh",
        "delete_confirm_long": "⚠️ WARNING:\nAre you sure you want to delete this bot?\n\n1. Trade history will be cleared\n2. Ensure positions are closed\n3. This cannot be undone",
        "unknown_error": "Unknown Error",
        "network_error_title": "⚠️ Network Connection Failed!",
        "network_error_hint": "Unable to fetch Kline or market data. Please check:\n1. Is VPN/Proxy enabled in Global Mode?\n2. Can the server access Binance API?\n3. Please try refreshing the page.",
        "no_permission_to_access_this_bot": "Access Denied: You do not own this bot",
        "instance_not_found": "Instance not found",
        "delete_rejected_due_to_open_position": "Delete Rejected: Open positions exist",
        "please_close_position_first": "Please close positions manually first",
        "delete_rejected_due_to_running_bot": "Delete Rejected: Bot is running",
        "please_stop_running_first": "Please stop the bot first",
        "dangerous_operation_intercepted": "Dangerous Operation Intercepted!",
        "flash_unauthorized_action": "Unauthorized Action",
        "amount_format_error": "Invalid Amount Format",
        "bot_not_found": "Bot not found",
        "connection_failed": "Connection Failed",
        "user_not_found": "User not found",
        "invalid_language": "Invalid Language Selection",
        "err_price_fetch": "Price Fetch Error",
        "err_price_fetch_retry": "Unable to fetch price, check network or retry later",
        "err_qty_too_small": "Qty Too Small",
        "err_order_amount_too_small": "Calculated order amount too small to execute",

        # === 14. Backend Logs & Status ===
        "log_base_order": "Base Order",
        "log_buy": "Buy",
        "log_sell": "Sell",
        "log_manual_buy": "Manual Buy",
        "log_manual_close": "Manual Close",
        "log_stop_loss": "Stop Loss",
        "log_take_profit": "Take Profit",
        "log_trailing_active": "Trailing Active",
        "log_trailing_hit": "Trailing Hit",
        "log_dca_buy": "DCA Buy",
        "log_grid_buy": "Grid Buy",
        "log_deposit": "Deposit",
        "status_running": "🟢 Running",
        "status_order_pending": "⏳ Pending",
        "status_starting": "🟡 Starting...",
        "status_stopped": "🛑 Stopped",
        "status_cooldown": "🧊 Cooldown",
        "status_waiting_range": "⏳ Waiting for Range",
        "status_insufficient_balance": "⚠️ Insufficient Balance",
        "msg_manual_buy_success": "Manual Buy Success",
        "msg_manual_close_success": "Manual Close Success",
        "base_order_market": "Base Order (Market)",
        "interval_reset": " (Range Reset)",
        "tracking_profits": "Trailing Profit",
        "just_traded_waiting_for_deviation": "⏳ Just traded, waiting for deviation...",
        "insufficient_balance_stop_replenishment": "⚠️ Balance exhausted, stopping replenishment",
        "first_order_area": "(First Order Area)",
        "state_fix_enter_pos": "State Fix: Entering Position Mode",
        "state_fix_reset_fake_pos": "State Fix: Resetting Fake Position",
        "waiting_for_kline": "Waiting for Kline data...",
        "auto_emergency_sl": "Auto Emergency SL generated",
        "trigger_be": "Break-even Triggered",
        "trailing_sl_up": "Trailing SL Moved Up",
        "trailing_sl_down": "Trailing SL Moved Down",
        "extreme_value": "Extreme Value",
        "detected": "Detected",
        "breakout_waiting_retest": "Breakout! Waiting for retest...",
        "scanning": "Scanning",
        "false_breakout_reset": "False breakout, resetting monitor",
        "retest_entry": "Retest Entry",
        "waiting_for_retest": "Waiting for retest... Distance",
        "trigger_take_profit_trailing": "TP Triggered, Trailing...",
        "need": "Need",
        "have": "Have",
        "manual_warehousing": "Manual Add Position",
        "direction_change_forbidden": "Direction switch forbidden",
        "please_manual_close_first": "Please [Manual Close All] before changing direction.",
        "direction_changed_bot_reset": "Direction changed, Bot state reset.",
        "changed_bot_reset": "Changed, range reset.",
        "range_changed_anchor_reset": "Range changed, anchor reset.",
        "status_reset": "Status Reset", 
        
        # --- 15. Layout & Folders [Missing Filled] ---
        "layout_bot": "Robot View",
        "layout_custom": "Custom View",
        "create_folder": "New Folder",
        "folder_name": "Folder Name",
        "select_bots": "Select Bots (Uncategorized only)",
        "uncategorized": "Uncategorized / Default",
        "delete_folder": "Delete Folder",
        "delete_folder_confirm": "Delete this folder? Bots inside will become uncategorized.",
        "move_to": "Move to...",
        "all_bots_categorized": "All bots are categorized!",
        "folder_created": "Folder Created",
        "folder_deleted": "Folder Deleted",
        "bot_moved": "Bot Moved",

        # [NEW] RSI Filter
        'first_order_settings': '📉 Entry Signal Settings',
        'first_order_conditions': 'First Order Conditions',
        'rsi_conditions_title': 'RSI Entry Conditions',
        'timeframe': 'Timeframe',
        'operator': 'Operator',
        'threshold': 'RSI Value',
        'active': 'Active',
        'add_condition': '+ Add Condition',
        'delete': 'Del',
        'op_lt': 'Less (<)',
        'op_gt': 'Greater (>)',
        'rsi_help': 'Bot opens new position ONLY if all active conditions are met. Does not affect DCA.',
        "hard_filters_title": "🛑 Hard Filters",
        "enable_stoch_filter": "Enable StochRSI (15m K<20/K>80)",
        "enable_bb_filter": "Enable BB Breakout (15m)",
        "enable_adx_filter": "Enable ADX Filter (4h ADX < 25)",
        "enable_vol_filter": "Enable Vol Spike (15m Vol > 1.5x Avg)",
        "filter_wait_vol": "⏳ Filter: Low Volume (Vol={v:.0f} < Target={t:.0f})",

        "filter_wait_stoch": "⏳ Filter: StochRSI wait (K={k:.1f})",
        "filter_wait_bb": "⏳ Filter: Price inside BB (Price={p:.2f}, Band={b:.2f})",
        "filter_wait_adx": "⏳ Filter: 4H ADX too high ({adx:.1f} > 25)",
        "filter_wait_msg": "⏳ Waiting for filters: {details}",

        'ma_trend_filter': '📈 MA Trend Filter',
        'ma_long': 'Long MA',
        'ma_short': 'Short MA',
        'ma_period': 'Period',
        'ma_type': 'Type',
        'ma_help': 'Long: Price > MA; Short: Price < MA.',
        'filter_wait_ma': '⏳ Filter: Price vs MA trend (Price={p:.2f}, MA={m:.2f})',
        'ma_period_hint': 'Middle number = count of past K-lines (e.g., 50/200).',
        'ma_type_hint': 'EMA (Exponential) is more sensitive to recent price; SMA is Simple Average.',

        # Data Download
        "download_history_data": "Download History Data",
        "download_modal_title": "📥 Download History from Exchange",
        "start_date": "Start Date",
        "end_date": "End Date",
        "download_tip": "ℹ️ Speed depends on network. Keep range under 3-6 months.",
        "coffin_warning": "⚠️ Note: Coffin bots only support 5m timeframes for backtesting!",
        "search_symbol_placeholder": "Type or Select Symbol (e.g. BTC/USDT)",
        "start_download_btn": "Start Download (.csv)",
        "downloading_wait": "⏳ Downloading... Do not close",
        "download_success_alert": "Success! You can now upload this CSV in Replay Mode.",
        "date_required": "Please select a start date",
        "download_error": "Download Failed",
        "start_date_end_date_required": "Start Date and End Date are required",
        "end_date_must_be_later": "End Date cannot be earlier than Start Date",
        "date_format_error": "Date format error",
        "missing_bot_id_or_file": "Missing bot_id or file",
        "backtest_completed": "Backtest Completed",
        "backtest_failed": "Backtest Failed",
        "please_upload_csv": "Please upload a CSV file first!",
        "running_dots": "Running...",
        "network_error_simple": "Network Error",
        "no_data_fetched": "No data fetched",
        "backtest_success_msg": "Backtest Completed!",

        'organizing_data': 'Organizing Data...',
        'loading_layout': 'Rendering Layout...'
    }
}